Created branch Lesson-2 and Add DZ Lesson-2
DanielGB-hub/geekshop-server pull request #2
Opened 2020-12-09 15:40 UTC by DanielGB-hub

Домашнее задание для Lesson-2

2020-12-10 13:33 UTC, Vokler requested changes

2020-12-10 13:33 UTC, Vokler commented on mainapp/views.py
> +        'style_link': 'css/index.css',
css файлы не обязательно тут передовать, лучше держать их в самих шаблонах

2020-12-10 13:33 UTC, Vokler commented on mainapp/views.py
> +def test_context(request):
Этот контролер в целом можно удалить, так как он был в основном для тестов

2020-12-14 12:31 UTC, DanielGB-hub commented on mainapp/views.py
> +        'style_link': 'css/index.css',
fixed

2020-12-14 12:31 UTC, DanielGB-hub commented on mainapp/views.py
> +def test_context(request):
fixed

2020-12-14 15:55 UTC, Vokler approved these changes

2020-12-14 15:56 UTC, merged