Add DZ 4
DanielGB-hub/geekshop-server pull request #5
Opened 2020-12-16 16:51 UTC by DanielGB-hub

Создал пулреквест ДЗ 4

2020-12-18 10:05 UTC, Vokler requested changes
Отвечая на ваш вопрос
_<a class="nav-link" href="{% url 'mainapp:products' %}">Каталог</a> вот этот код в файле base.html в таком вот виде я не запустил._

Так не получится `mainapp:products`, потому что у вас в mainapp.urls ничего нет.
+ первая полвина, где вы пишите mainapp - там обычно указывается namspace, а он у вас products d geekshop.url

2020-12-18 10:05 UTC, Vokler commented on authapp/forms.py
> +        self.fields['password'].widget.attrs['class'] = 'form-control py-4'
У вас повторяющиеся куски кода, можно их занести в цикл for
https://ru.wikipedia.org/wiki/Don’t_repeat_yourself

2020-12-18 10:05 UTC, Vokler commented on authapp/views.py
> +        'style_link': 'css/auth.css',
Не стоит передавать стили и скрипты в контроллере. Это обычно выносится все в шаблон

2020-12-20 12:58 UTC, DanielGB-hub commented on authapp/forms.py
> +        self.fields['password'].widget.attrs['class'] = 'form-control py-4'
переделал

2020-12-20 12:59 UTC, DanielGB-hub commented on authapp/views.py
> +        'style_link': 'css/auth.css',
переделал)

2020-12-21 14:23 UTC, Vokler approved these changes

2020-12-21 14:23 UTC, merged